### ISSUE TITLE
Change photo uploads elements to <input />

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/comicfun#11]
Currently, the "take a picture" and "upload file" sections inside /tool.js are div elements.  These need to be input elements with file type image.  The onClick, and hover effects should stay.

**Comment by akshay-patade** [comment]
HI @brandonbyr4 ,

Can i work on this issue?

Signed-off-by: Akshay Patade <akshaypatade@gmail.com>

**Comment by Halim-Shams** [comment]
Hey @akshay-patade  I just changed it, you can take a look

**Comment by Halim-Shams** [comment]
Hey @akshay-patade  I just changed the divs to input type of file, you can take a look #18

**Comment by akshay-patade** [comment]
> Hey @akshay-patade  I just changed the divs to input type of file, you can take a look #18 

Hi @Halim-Shams , Sure. I will have a look at it.
