### ISSUE TITLE
Create state for quality and file type

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/comicfun#25]
Inside /tool.js, there is currently a handleQuality and handleFileType function.  Please import useState, and create a state value for these instead, so that they can controlled adaptively.

**Comment by elyessAR** [comment]
you can assign me this one @brandonbyr4 it's clear enough to get me started on this project :)

**Comment by brandonbyr4** [comment]
Thank you @elyessAR.  Assigned 👍. Feel free to ask any questions if you need clarification.
