### ISSUE TITLE
Change upload headers to text-2xl

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/comicfun#28]
In /tool.js, the upload headers (h1 & h2) are currently text-3xl.  Please add the class md:text-2xl to both headers, so that on mobile views they shrink to this size.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by brandonbyr4** [comment]
@tarunsamanta2k20 sure, assigned.
