### ISSUE TITLE
Add SVG fill on hover.

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/comicfun#7]
in /tool.js, the sidebar icons do not fill on hover.  This may require tailwind link to accomplish this.  When the overall link component is hovered, fill should be applied to the icon.

**Comment by sharmashubam** [comment]
Hi @brandonbyr4 , I would like to work on this issue.

**Comment by brandonbyr4** [comment]
Hi @sharmashubam, thanks.  Assigned.
