### ISSUE TITLE
Add coming soon function for button controls

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/comicfun#9]
In /tool.js, the "quality" and "file" buttons should have an onClick that gives a "Coming soon!" alert, just like the generate portrait button.

**Comment by akshay-patade** [comment]
Hi @brandonbyr4,

Can i work on this issue?
Signed-off-by: Akshay Patade <akshaypatade@gmail.com>

**Comment by brandonbyr4** [comment]
@akshay-patade assigned, thanks.

**Comment by akshay-patade** [comment]
Hi @brandonbyr4 ,

What should be the name of the onClick functions for "quality" and "file" buttons.

Signed-off-by: Akshay Patade <akshaypatade@gmail.com>

**Comment by brandonbyr4** [comment]
They can be called "handleQuality", and "handleFileType".  Thank you for clarifying 👍
